### ISSUE TITLE
@_destroy causes the server to break

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#105]
`@_destroy` leads to the responder calling `@head` which is not defined.

This causes the server to fail.

This should be changed to `@controller.head``

**Comment by sebastianhoitz** [comment]
This is fixed in pull request #106.

**Comment by michaelsbradleyjr** [comment]
This is still failing for me on Ubuntu 11.10, node v0.6.15, mongod v2.0.4, fresh clone of tower, npm test:

```
$ npm test

> tower@0.4.0-12 test /home/michael/repos/other/tower
> node_modules/mocha/bin/mocha $(find test -name "*Test.coffee")

...

3) Issue105 handle request with unknown format:
     expected { attributes: 
   { id: 4f9a3a7d89fc3a6c0900047c,
     title: null,
     rating: 4,
     type: 'Post',
     tags: [],
     meta: null,
     userIds: [],
     userId: null,
     createdAt: Fri, 27 Apr 2012 06:19:41 GMT,
     updatedAt: Fri, 27 Apr 2012 06:19:41 GMT,
     likeCount: 0 },
  relations: {},
  changes: 
   { before: 
      { title: null,
        rating: null,
        type: 'Post',
        tags: [],
        meta: null,
        userIds: [],
        userId: undefined,
        createdAt: undefined,
        updatedAt: undefined,
        likeCount: 0,
        id: undefined },
     after: { '$set': [Object] },
     title: [ undefined, null ],
     rating: [ undefined, 4 ],
     tags: [ [], [] ],
     meta: [ undefined, null ],
     userIds: [ [], [] ],
     userId: [ undefined, null ],
     createdAt: [ undefined, Fri, 27 Apr 2012 06:19:41 GMT ],
     updatedAt: [ undefined, Fri, 27 Apr 2012 06:19:41 GMT ],
     id: [ undefined, 4f9a3a7d89fc3a6c0900047c ] },
  errors: {},
  operations: 
   [ { '$set': [Object] },
     { '$set': [Object] },
     { '$set': [Object] },
     { '$set': [Object] },
     { '$set': [Object] },
     { '$set': [Object] },
     { '$set': [Object] },
     { '$set': [Object] },
     { '$set': [Object] },
     { '$set': [Object] },
     { '$set': [Object] } ],
  operationIndex: 11,
  readOnly: false,
  persistent: true } to equal undefined



npm ERR! tower@0.4.0-12 test: `node_modules/mocha/bin/mocha $(find test -name "*Test.coffee")`
npm ERR! `sh "-c" "node_modules/mocha/bin/mocha $(find test -name \"*Test.coffee\")"` failed with 3
...
```
